@Host= http://localhost:3030/v1

###
GET {{Host}}/contacts


###

POST {{Host}}/contacts
content-type: application/json

  {
    "name": "Ada Love",
    "number": "39-44-5323523"
  }

###

PATCH  {{Host}}/contacts/1
content-type: application/json

  {
    "name": "Arto Hellas",
    "number": "39-00-5323523"
  }

###


DELETE {{Host}}/contacts/2